import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import Footer from "@/components/Footer";
import "../assests/globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-black-200 min-h-[100dvh] grid grid-rows-[auto_1fr_auto]">
          
          <div>
            <Link href="/about-us">About Us</Link> | <Link href="/">Home</Link>
          </div>

          <main>
            {children}
          </main>

          <Footer/>
        </div>
        
      </body>
    </html>
  );
}
